name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  better_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.10
  visibility_detector: ^0.3.3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter:
  assets:
    - assets/
  uses-material-design: true