name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  #better_player: any
  better_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.1
  visibility_detector: 0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
  uses-material-design: true