name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.29+1
authors:
  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_iconic_flutter: ^0.3.0
  wakelock: ^0.2.0+1
  pedantic: ^1.8.0
  meta: ^1.2.3
  flutter_widget_from_html_core: ^0.5.0+5
  flutter_hls_parser: ^1.0.0
  visibility_detector: ^0.1.5

##Fixes wakelock issue: https://github.com/creativecreatorormaybenot/wakelock/issues/48
dependency_overrides:
  import_js_library:
    git:
      url: https://github.com/simpleclub-extended/flutter_web_import_js_library
      ref: fix-android


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: FLTBetterPlayerPlugin
