name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-format:
      name: Check format using flutter format
      runs-on: ubuntu-latest
      container: cirrusci/flutter:stable

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Check format
          run: flutter format -n --set-exit-if-changed .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies for example
        run: flutter pub get
        working-directory: example
      - name: Lint using flutter analyze
        run: flutter analyze
